title: Development
description: Language and Framework Training Notes
theme: jekyll-theme-hacker
domain: ferretedheart.github.io
url: https://ferretedheart.github.io
baseurl: /ProgrammingNotes/
markdown: kramdown
